cc = gcc
CFLAGS = -g -Wall
SRCS = factorize.c narcissus.c prime.c rabit.c score.c lcdAndlcm.c count.c add.c count.c perfectNum.c monkeyKing.c fall.c
TARGETS = $(SRCS:%.c=%)
all:$(TARGETS)
clean:
	rm -rf $(TARGETS) $(OBJECTS)
echo:
	@echo $(TARGETS)
